In [ ]:
import numpy as np

f1 = r'C:\Users\buggyr\Mosaic_Experiments\data\processed\Training Images 3\Training_Patches32\input_img_patch.npy'

orig = np.load(f1)
orig = (orig/127.5) - 1
#shape = [n,64,64,3]
num = orig.shape[0]
ls = []
for i in range (0,num-1):
    print(i)
    r = orig[i,:,:,0]
    g = orig[i,:,:,1]
    b = orig[i,:,:,2]
    
    Y = 0.299 * r + 0.587 * g + 0.114 * b
    U = 0.492 * (b - Y)
    V = 0.877 * (r - Y)
    
    ls.append((np.stack((Y,U,V))).astype(np.float32))
    
np.save(r'C:\Users\buggyr\Mosaic_Experiments\data\processed\input_yuv32', np.stack(ls,0))    

print('done')




In [15]:
import cv2
import numpy as np

q = (np.ones((5,5,3))).astype(np.uint8)
print(q.shape)

yb = cv2.cvtColor(q,cv2.COLOR_YUV2BGR)

by = cv2.cvtColor(q,cv2.COLOR_BGR2YUV)

m1= np.array([[0.299, 0.587, 0.114],[-0.147, - 0.289, 0.436],[0.615,-0.515,-0.1]])

yb1 = np.dot(q,m1)
print(yb1)
print(yb)

m = np.array([[ 0.11400, 0.436, -0.1],
                 [0.58700, -0.289, -0.515],
                 [ 0.29900, -0.147,  0.615]])

(5, 5, 3)
[[[ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]]

 [[ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]]

 [[ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]]

 [[ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]]

 [[ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]
  [ 0.767 -0.217  0.45 ]]]
[[[  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]]

 [[  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]]

 [[  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]]

 [[  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]
  [  0 125   0]]

 [[  0 125   0]
  [  0 125 

array([[[  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128]],

       [[  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128]],

       [[  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128]],

       [[  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128]],

       [[  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128],
        [  1, 128, 128]]], dtype=uint8)